package com.org.mntr.dto;
// default package

// Generated 11-Aug-2017 16:11:48 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * MailDetailsDto generated by hbm2java
 */
public class MailDetailsDto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long mailRefId;
	private String fromAddress;
	private String toAddress;
	private Date sentDt;
	private String deliveryStatus;

	public MailDetailsDto() {
	}

	public MailDetailsDto(String fromAddress, String toAddress, Date sentDt, String deliveryStatus) {
		this.fromAddress = fromAddress;
		this.toAddress = toAddress;
		this.sentDt = sentDt;
		this.deliveryStatus = deliveryStatus;
	}

	public Long getMailRefId() {
		return this.mailRefId;
	}

	public void setMailRefId(Long mailRefId) {
		this.mailRefId = mailRefId;
	}

	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	public Date getSentDt() {
		return this.sentDt;
	}

	public void setSentDt(Date sentDt) {
		this.sentDt = sentDt;
	}

	public String getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

}
