package com.org.mntr.dto;
// default package

// Generated 11-Aug-2017 16:11:48 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * MenuDetailsDto generated by hbm2java
 */
public class MenuDetailsDto implements java.io.Serializable, Comparable<MenuDetailsDto> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long menuId;
	private String menuName;
	private Integer menuType;
	private Integer menuPriority;
	private Integer status;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;
	private Long menuMaster;
	private String menuDesc;
	private String url;
	private String iconName;
	private Long userDefMenuId;
	private Integer hasChild;
	private Integer opsType;

	public MenuDetailsDto() {
	}

	public MenuDetailsDto(String menuName, Integer menuType, Integer menuPriority, Integer status, String createdBy,
			Date createdDt, String modifiedBy, Date modifiedDt, Long menuMaster, String menuDesc, String url,
			String iconName, Long userDefMenuId, Integer hasChild) {
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuPriority = menuPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.menuMaster = menuMaster;
		this.menuDesc = menuDesc;
		this.url = url;
		this.iconName = iconName;
		this.userDefMenuId = userDefMenuId;
		this.hasChild = hasChild;
	}

	@Override
	public int compareTo(MenuDetailsDto o) {
		return this.menuPriority - o.getMenuPriority();
	}

	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	public Integer getMenuPriority() {
		return this.menuPriority;
	}

	public void setMenuPriority(Integer menuPriority) {
		this.menuPriority = menuPriority;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	public Long getMenuMaster() {
		return this.menuMaster;
	}

	public void setMenuMaster(Long menuMaster) {
		this.menuMaster = menuMaster;
	}

	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIconName() {
		return this.iconName;
	}

	public void setIconName(String iconName) {
		this.iconName = iconName;
	}

	public Long getUserDefMenuId() {
		return this.userDefMenuId;
	}

	public void setUserDefMenuId(Long userDefMenuId) {
		this.userDefMenuId = userDefMenuId;
	}

	public Integer getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(Integer hasChild) {
		this.hasChild = hasChild;
	}

	public Integer getOpsType() {
		return opsType;
	}

	public void setOpsType(Integer opsType) {
		this.opsType = opsType;
	}
}
