package com.org.mntr.dto;
// default package

// Generated 11-Aug-2017 16:11:48 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

import com.org.mntr.constants.SSValidationConfig;
import com.org.mntr.validators.FieldValid;

/**
 * PasswordDetailsDto generated by hbm2java
 */
@FieldValid(firstField = "password", secondField = "cPassword")
public class PasswordDetailsDto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long passRefId;
	private String pwdUuid;
	private Date uuidGenerationDt;
	private String hashPwd;
	private Date modifiedDt;
	private Date createdDt;
	private String createdBy;
	private String modifiedBy;
	private String encryptedPwd;
	private Integer status;

	@NotBlank
	@NotEmpty
	@NotNull
	@Size(min = SSValidationConfig.passGeneralMin, max = SSValidationConfig.passGeneralMax)
	@Pattern(regexp = SSValidationConfig.passGeneralPattern)
	private String password;

	@NotBlank
	@NotEmpty
	@NotNull
	@Size(min = SSValidationConfig.passGeneralMin, max = SSValidationConfig.passGeneralMax)
	@Pattern(regexp = SSValidationConfig.passGeneralPattern)
	private String cPassword;

	public PasswordDetailsDto() {
	}

	public PasswordDetailsDto(String pwdUuid, Date uuidGenerationDt, Date modifiedDt, Date createdDt, String createdBy,
			String modifiedBy, Integer status) {
		this.pwdUuid = pwdUuid;
		this.uuidGenerationDt = uuidGenerationDt;
		this.modifiedDt = modifiedDt;
		this.createdDt = createdDt;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.status = status;
	}

	public Long getPassRefId() {
		return this.passRefId;
	}

	public void setPassRefId(Long passRefId) {
		this.passRefId = passRefId;
	}

	public String getPwdUuid() {
		return this.pwdUuid;
	}

	public void setPwdUuid(String pwdUuid) {
		this.pwdUuid = pwdUuid;
	}

	public Date getUuidGenerationDt() {
		return this.uuidGenerationDt;
	}

	public void setUuidGenerationDt(Date uuidGenerationDt) {
		this.uuidGenerationDt = uuidGenerationDt;
	}

	public String getHashPwd() {
		return this.hashPwd;
	}

	public void setHashPwd(String hashPwd) {
		this.hashPwd = hashPwd;
	}

	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getEncryptedPwd() {
		return this.encryptedPwd;
	}

	public void setEncryptedPwd(String encryptedPwd) {
		this.encryptedPwd = encryptedPwd;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getcPassword() {
		return cPassword;
	}

	public void setcPassword(String cPassword) {
		this.cPassword = cPassword;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
