package com.org.mntr.dto;
// default package

// Generated 11-Aug-2017 16:11:48 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

import com.org.mntr.constants.SSValidationConfig;

/**
 * TemplateDto generated by hbm2java
 */
public class TemplateDto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long templateId;

	@NotNull
	@NotEmpty
	@NotBlank
	@Size(min = SSValidationConfig.textGeneralMin, max = SSValidationConfig.textGeneralMax)
	private String hostName;
	@NotNull
	private Long checkInterval;
	@NotNull
	private Long retryIntervel;
	@NotNull
	private Long maxCheckAttempts;
	@NotNull
	private Long alertsGroupId;
	@NotNull
	private Integer status;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;
	private String description;

	public TemplateDto() {
	}

	public TemplateDto(String hostName, Long checkInterval, Long retryIntervel, Long maxCheckAttempts,
			Long alertsGroupId, Integer status, String createdBy, Date createdDt, String modifiedBy, Date modifiedDt,
			String description) {
		this.hostName = hostName;
		this.checkInterval = checkInterval;
		this.retryIntervel = retryIntervel;
		this.maxCheckAttempts = maxCheckAttempts;
		this.alertsGroupId = alertsGroupId;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.description = description;
	}

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public Long getCheckInterval() {
		return this.checkInterval;
	}

	public void setCheckInterval(Long checkInterval) {
		this.checkInterval = checkInterval;
	}

	public Long getRetryIntervel() {
		return this.retryIntervel;
	}

	public void setRetryIntervel(Long retryIntervel) {
		this.retryIntervel = retryIntervel;
	}

	public Long getMaxCheckAttempts() {
		return this.maxCheckAttempts;
	}

	public void setMaxCheckAttempts(Long maxCheckAttempts) {
		this.maxCheckAttempts = maxCheckAttempts;
	}

	public Long getAlertsGroupId() {
		return this.alertsGroupId;
	}

	public void setAlertsGroupId(Long alertsGroupId) {
		this.alertsGroupId = alertsGroupId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
