package com.org.mntr.dto;

import java.util.ArrayList;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

import com.org.mntr.constants.SSValidationConfig;
import com.org.mntr.validators.Phone;

/**
 * UserInfoDto generated by hbm2java
 */
public class UserInfoDto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long userKey;

	@NotNull
	@NotEmpty
	@NotBlank
	@Size(min = SSValidationConfig.textGeneralMin, max = SSValidationConfig.textGeneralMax)
	private String userId;

	@NotNull
	@NotEmpty
	@NotBlank
	@Size(min = SSValidationConfig.textGeneralMin, max = SSValidationConfig.textGeneralMax)
	private String username;
	private Date lastLoginDt;
	private Integer lockStatus;
	private Integer invalidPassAttempts;
	private Integer status;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;
	private Integer loginType;

	@NotNull
	@NotEmpty
	@NotBlank
	@Email
	private String email;

	@NotNull
	@NotEmpty
	@NotBlank
	@Phone
	private String phoneNo;
	private String userLogoName;

	private List<String> roles = new ArrayList<String>();
	private List<MenuDetailsDto> parentURLList = new ArrayList<MenuDetailsDto>();
	private List<MenuDetailsDto> childURLList = new ArrayList<MenuDetailsDto>();
	private String conCatRoles;
	private String hashPwd;
	private String pwdUuid;
	private Long roleId;

	public UserInfoDto() {
	}

	public UserInfoDto(String userId, String username, Date lastLoginDt, Integer lockStatus,
			Integer invalidPassAttempts, Integer status, String createdBy, Date createdDt, String modifiedBy,
			Date modifiedDt, Integer loginType, String email, String phoneNo, String userLogoName) {
		this.userId = userId;
		this.username = username;
		this.lastLoginDt = lastLoginDt;
		this.lockStatus = lockStatus;
		this.invalidPassAttempts = invalidPassAttempts;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.loginType = loginType;
		this.email = email;
		this.phoneNo = phoneNo;
		this.userLogoName = userLogoName;
	}

	public UserInfoDto(Long userKey, String userId, String username, Date lastLoginDt, Integer lockStatus,
			Integer invalidPassAttempts, Integer status, String createdBy, Date createdDt, String modifiedBy,
			Date modifiedDt, Integer loginType, String email, String phoneNo, String userLogoName, List<String> roles,
			List<MenuDetailsDto> parentURLList, List<MenuDetailsDto> childURLList, String conCatRoles, String hashPwd) {
		super();
		this.userKey = userKey;
		this.userId = userId;
		this.username = username;
		this.lastLoginDt = lastLoginDt;
		this.lockStatus = lockStatus;
		this.invalidPassAttempts = invalidPassAttempts;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.loginType = loginType;
		this.email = email;
		this.phoneNo = phoneNo;
		this.userLogoName = userLogoName;
		this.roles = roles;
		this.parentURLList = parentURLList;
		this.childURLList = childURLList;
		this.conCatRoles = conCatRoles;
		this.hashPwd = hashPwd;
	}

	public Long getUserKey() {
		return this.userKey;
	}

	public void setUserKey(Long userKey) {
		this.userKey = userKey;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getLastLoginDt() {
		return this.lastLoginDt;
	}

	public void setLastLoginDt(Date lastLoginDt) {
		this.lastLoginDt = lastLoginDt;
	}

	public Integer getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(Integer lockStatus) {
		this.lockStatus = lockStatus;
	}

	public Integer getInvalidPassAttempts() {
		return this.invalidPassAttempts;
	}

	public void setInvalidPassAttempts(Integer invalidPassAttempts) {
		this.invalidPassAttempts = invalidPassAttempts;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	public Integer getLoginType() {
		return this.loginType;
	}

	public void setLoginType(Integer loginType) {
		this.loginType = loginType;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getUserLogoName() {
		return this.userLogoName;
	}

	public void setUserLogoName(String userLogoName) {
		this.userLogoName = userLogoName;
	}

	public List<String> getRoles() {
		return roles;
	}

	public void setRoles(List<String> roles) {
		this.roles = roles;
	}

	public List<MenuDetailsDto> getParentURLList() {
		return parentURLList;
	}

	public void setParentURLList(List<MenuDetailsDto> parentURLList) {
		this.parentURLList = parentURLList;
	}

	public List<MenuDetailsDto> getChildURLList() {
		return childURLList;
	}

	public void setChildURLList(List<MenuDetailsDto> childURLList) {
		this.childURLList = childURLList;
	}

	public String getConCatRoles() {
		return conCatRoles;
	}

	public void setConCatRoles(String conCatRoles) {
		this.conCatRoles = conCatRoles;
	}

	public String getHashPwd() {
		return hashPwd;
	}

	public void setHashPwd(String hashPwd) {
		this.hashPwd = hashPwd;
	}

	public String getPwdUuid() {
		return pwdUuid;
	}

	public void setPwdUuid(String pwdUuid) {
		this.pwdUuid = pwdUuid;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

}
