package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MailDetails generated by hbm2java
 */
@Entity
@Table(name = "mail_details", catalog = "rdev")
public class MailDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long mailRefId;
	private String fromAddress;
	private String toAddress;
	private Date sentDt;
	private String deliveryStatus;

	public MailDetails() {
	}

	public MailDetails(String fromAddress, String toAddress, Date sentDt, String deliveryStatus) {
		this.fromAddress = fromAddress;
		this.toAddress = toAddress;
		this.sentDt = sentDt;
		this.deliveryStatus = deliveryStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAIL_REF_ID", unique = true, nullable = false)
	public Long getMailRefId() {
		return this.mailRefId;
	}

	public void setMailRefId(Long mailRefId) {
		this.mailRefId = mailRefId;
	}

	@Column(name = "FROM_ADDRESS", nullable = false, length = 250)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "TO_ADDRESS", nullable = false, length = 250)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENT_DT", nullable = false, length = 19)
	public Date getSentDt() {
		return this.sentDt;
	}

	public void setSentDt(Date sentDt) {
		this.sentDt = sentDt;
	}

	@Column(name = "DELIVERY_STATUS", nullable = false, length = 45)
	public String getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

}
