package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MenuDetails generated by hbm2java
 */
@Entity
@Table(name = "menu_details", catalog = "rdev", uniqueConstraints = { @UniqueConstraint(columnNames = "MENU_NAME"),
		@UniqueConstraint(columnNames = "USER_DEF_MENU_ID") })
public class MenuDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long menuId;
	private String menuName;
	private Integer menuType;
	private Integer menuPriority;
	private Integer status;
	private Long createdBy;
	private Date createdDt;
	private Long modifiedBy;
	private Date modifiedDt;
	private Long menuMaster;
	private String menuDesc;
	private String url;
	private String iconName;
	private Long userDefMenuId;
	private Integer hasChild;
	private Set<RoleMenuMapping> roleMenuMappings = new HashSet<RoleMenuMapping>(0);

	public MenuDetails() {
	}

	public MenuDetails(String menuName, Integer menuType, Integer menuPriority, Integer status, Long createdBy,
			Date createdDt, Long modifiedBy, Date modifiedDt, Long menuMaster, String menuDesc, String url,
			String iconName, Long userDefMenuId, Integer hasChild) {
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuPriority = menuPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.menuMaster = menuMaster;
		this.menuDesc = menuDesc;
		this.url = url;
		this.iconName = iconName;
		this.userDefMenuId = userDefMenuId;
		this.hasChild = hasChild;
	}

	public MenuDetails(String menuName, Integer menuType, Integer menuPriority, Integer status, Long createdBy,
			Date createdDt, Long modifiedBy, Date modifiedDt, Long menuMaster, String menuDesc, String url,
			String iconName, Long userDefMenuId, Integer hasChild, Set<RoleMenuMapping> roleMenuMappings) {
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuPriority = menuPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.menuMaster = menuMaster;
		this.menuDesc = menuDesc;
		this.url = url;
		this.iconName = iconName;
		this.userDefMenuId = userDefMenuId;
		this.hasChild = hasChild;
		this.roleMenuMappings = roleMenuMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MENU_ID", unique = true, nullable = false)
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "MENU_NAME", unique = true, nullable = false, length = 150)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "MENU_TYPE", nullable = false)
	public Integer getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	@Column(name = "MENU_PRIORITY", nullable = false)
	public Integer getMenuPriority() {
		return this.menuPriority;
	}

	public void setMenuPriority(Integer menuPriority) {
		this.menuPriority = menuPriority;
	}

	@Column(name = "STATUS", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", nullable = false, length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "MODIFIED_BY", nullable = false)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", nullable = false, length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	@Column(name = "MENU_MASTER", nullable = false)
	public Long getMenuMaster() {
		return this.menuMaster;
	}

	public void setMenuMaster(Long menuMaster) {
		this.menuMaster = menuMaster;
	}

	@Column(name = "MENU_DESC", nullable = false, length = 150)
	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	@Column(name = "URL", nullable = false, length = 250)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ICON_NAME", nullable = false, length = 50)
	public String getIconName() {
		return this.iconName;
	}

	public void setIconName(String iconName) {
		this.iconName = iconName;
	}

	@Column(name = "USER_DEF_MENU_ID", unique = true, nullable = false)
	public Long getUserDefMenuId() {
		return this.userDefMenuId;
	}

	public void setUserDefMenuId(Long userDefMenuId) {
		this.userDefMenuId = userDefMenuId;
	}

	@Column(name = "HAS_CHILD", nullable = false)
	public Integer getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(Integer hasChild) {
		this.hasChild = hasChild;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuDetails")
	public Set<RoleMenuMapping> getRoleMenuMappings() {
		return this.roleMenuMappings;
	}

	public void setRoleMenuMappings(Set<RoleMenuMapping> roleMenuMappings) {
		this.roleMenuMappings = roleMenuMappings;
	}

}
