package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PasswordDetails generated by hbm2java
 */
@Entity
@Table(name = "password_details", catalog = "rdev", uniqueConstraints = { @UniqueConstraint(columnNames = "PWD_UUID"),
		@UniqueConstraint(columnNames = "USER_KEY") })
public class PasswordDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long passRefId;
	private UserInfo userInfo;
	private String pwdUuid;
	private Date uuidGenerationDt;
	private String hashPwd;
	private Date modifiedDt;
	private Date createdDt;
	private Long createdBy;
	private Long modifiedBy;
	private String encryptedPwd;
	private Integer status;

	public PasswordDetails() {
	}

	public PasswordDetails(UserInfo userInfo, String pwdUuid, Date uuidGenerationDt, Date modifiedDt, Date createdDt,
			Long createdBy, Long modifiedBy, Integer status) {
		this.userInfo = userInfo;
		this.pwdUuid = pwdUuid;
		this.uuidGenerationDt = uuidGenerationDt;
		this.modifiedDt = modifiedDt;
		this.createdDt = createdDt;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.status = status;
	}

	public PasswordDetails(UserInfo userInfo, String pwdUuid, Date uuidGenerationDt, String hashPwd, Date modifiedDt,
			Date createdDt, Long createdBy, Long modifiedBy, String encryptedPwd, Integer status) {
		this.userInfo = userInfo;
		this.pwdUuid = pwdUuid;
		this.uuidGenerationDt = uuidGenerationDt;
		this.hashPwd = hashPwd;
		this.modifiedDt = modifiedDt;
		this.createdDt = createdDt;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.encryptedPwd = encryptedPwd;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PASS_REF_ID", unique = true, nullable = false)
	public Long getPassRefId() {
		return this.passRefId;
	}

	public void setPassRefId(Long passRefId) {
		this.passRefId = passRefId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_KEY", unique = true, nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "PWD_UUID", unique = true, nullable = false, length = 250)
	public String getPwdUuid() {
		return this.pwdUuid;
	}

	public void setPwdUuid(String pwdUuid) {
		this.pwdUuid = pwdUuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UUID_GENERATION_DT", nullable = false, length = 19)
	public Date getUuidGenerationDt() {
		return this.uuidGenerationDt;
	}

	public void setUuidGenerationDt(Date uuidGenerationDt) {
		this.uuidGenerationDt = uuidGenerationDt;
	}

	@Column(name = "HASH_PWD", length = 250)
	public String getHashPwd() {
		return this.hashPwd;
	}

	public void setHashPwd(String hashPwd) {
		this.hashPwd = hashPwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", nullable = false, length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", nullable = false, length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MODIFIED_BY", nullable = false)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ENCRYPTED_PWD", length = 250)
	public String getEncryptedPwd() {
		return this.encryptedPwd;
	}

	public void setEncryptedPwd(String encryptedPwd) {
		this.encryptedPwd = encryptedPwd;
	}

	@Column(name = "STATUS", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
