package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PasswordHistoryDetails generated by hbm2java
 */
@Entity
@Table(name = "password_history_details", catalog = "rdev")
public class PasswordHistoryDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pwdHisRefId;
	private UserInfo userInfo;
	private String password;
	private Date pwdCreationDt;

	public PasswordHistoryDetails() {
	}

	public PasswordHistoryDetails(Long pwdHisRefId, UserInfo userInfo, String password, Date pwdCreationDt) {
		this.pwdHisRefId = pwdHisRefId;
		this.userInfo = userInfo;
		this.password = password;
		this.pwdCreationDt = pwdCreationDt;
	}

	@Id

	@Column(name = "PWD_HIS_REF_ID", unique = true, nullable = false)
	public Long getPwdHisRefId() {
		return this.pwdHisRefId;
	}

	public void setPwdHisRefId(Long pwdHisRefId) {
		this.pwdHisRefId = pwdHisRefId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_KEY", nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "PASSWORD", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PWD_CREATION_DT", nullable = false, length = 19)
	public Date getPwdCreationDt() {
		return this.pwdCreationDt;
	}

	public void setPwdCreationDt(Date pwdCreationDt) {
		this.pwdCreationDt = pwdCreationDt;
	}

}
