package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleMenuMapping generated by hbm2java
 */
@Entity
@Table(name = "role_menu_mapping", catalog = "rdev")
public class RoleMenuMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long rmMappingId;
	private MenuDetails menuDetails;
	private UserRole userRole;

	public RoleMenuMapping() {
	}

	public RoleMenuMapping(MenuDetails menuDetails, UserRole userRole) {
		this.menuDetails = menuDetails;
		this.userRole = userRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RM_MAPPING_ID", unique = true, nullable = false)
	public Long getRmMappingId() {
		return this.rmMappingId;
	}

	public void setRmMappingId(Long rmMappingId) {
		this.rmMappingId = rmMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_ID", nullable = false)
	public MenuDetails getMenuDetails() {
		return this.menuDetails;
	}

	public void setMenuDetails(MenuDetails menuDetails) {
		this.menuDetails = menuDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

}
