package com.org.mntr.entity;
// Generated 11-Aug-2017 13:10:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRoleMapping generated by hbm2java
 */
@Entity
@Table(name = "user_role_mapping", catalog = "rdev", uniqueConstraints = @UniqueConstraint(columnNames = "USER_KEY"))
public class UserRoleMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long urMappingId;
	private UserInfo userInfo;
	private UserRole userRole;

	public UserRoleMapping() {
	}

	public UserRoleMapping(UserInfo userInfo, UserRole userRole) {
		this.userInfo = userInfo;
		this.userRole = userRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UR_MAPPING_ID", unique = true, nullable = false)
	public Long getUrMappingId() {
		return this.urMappingId;
	}

	public void setUrMappingId(Long urMappingId) {
		this.urMappingId = urMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "USER_KEY", unique = true, nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

}
